name: Deploy to AWS

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to ECS
        env:
          CLUSTER_NAME: ${{ secrets.CLUSTER_NAME }}           # ECS cluster name from your setup
          SERVICE_NAME: ${{ secrets.SERVICE_NAME }}          # ECS service name (you can adjust accordingly)
          CONTAINER_NAME: ${{ secrets.CONTAINER_NAME }}                 # Container name in task definition
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}  # ECR repo from secrets
          IMAGE_TAG: ${{ github.event.workflow_run.head_sha }}
        run: |
          echo "Updating ECS service with new image..."

          # Fetch current task definition JSON
          TASK_DEF_JSON=$(aws ecs describe-task-definition --task-definition $SERVICE_NAME)

          # Update container image in the task definition
          NEW_TASK_DEF=$(echo $TASK_DEF_JSON | jq --arg IMAGE "$ECR_REPOSITORY:$IMAGE_TAG" '
            .taskDefinition.containerDefinitions[] |=
              if .name == "'"$CONTAINER_NAME"'" then .image = $IMAGE else . end |
            {
              family: .taskDefinition.family,
              taskRoleArn: .taskDefinition.taskRoleArn,
              executionRoleArn: .taskDefinition.executionRoleArn,
              networkMode: .taskDefinition.networkMode,
              containerDefinitions: .taskDefinition.containerDefinitions,
              requiresCompatibilities: .taskDefinition.requiresCompatibilities,
              cpu: .taskDefinition.cpu,
              memory: .taskDefinition.memory
            }
          ')

          # Register new task definition revision
          NEW_TASK_DEF_ARN=$(aws ecs register-task-definition --cli-input-json "$NEW_TASK_DEF" --query 'taskDefinition.taskDefinitionArn' --output text)

          echo "New task definition registered: $NEW_TASK_DEF_ARN"

          # Update ECS service to use the new task definition
          aws ecs update-service --cluster $CLUSTER_NAME --service $SERVICE_NAME --task-definition $NEW_TASK_DEF_ARN

          echo "Service updated successfully."