name: Deploy Database

on:
  workflow_dispatch:

env:
  IMAGE_TAG: ${{ github.sha }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Install MySQL client
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-client

      - name: Get public IP of runner
        id: ip
        run: |
          echo "IP=$(curl -s https://checkip.amazonaws.com)" >> $GITHUB_ENV

      - name: Allow temporary MySQL access from runner IP
        run: |
          echo "Authorizing $IP for MySQL access..."
          aws ec2 authorize-security-group-ingress \
            --group-id ${{ secrets.RDS_SECURITY_GROUP_ID }} \
            --protocol tcp \
            --port 3306 \
            --cidr $IP/32 

      - name: Make RDS publicly accessible (temporarily)
        run: |
          aws rds modify-db-instance \
            --db-instance-identifier ${{ secrets.DB_IDENTIFIER }} \
            --publicly-accessible \
            --apply-immediately

      - name: Wait for DB to become available
        run: |
          aws rds wait db-instance-available \
            --db-instance-identifier ${{ secrets.DB_IDENTIFIER }}

      - name: Run init.sql on RDS
        run: |
          echo "Connecting to $DB_HOST..."
          mysql -h ${{ secrets.RDS_HOST }} -P ${{ secrets.RDS_PORT }} -u ${{ secrets.RDS_USER }} -p${{ secrets.RDS_PASSWORD }} < ${{ github.workspace }}/docker/mysql/init.sql

      - name: Revoke MySQL access after job
        if: always()
        run: |
          echo "Revoking access for $IP..."
          aws ec2 revoke-security-group-ingress \
            --group-id ${{ secrets.RDS_SECURITY_GROUP_ID }} \
            --protocol tcp \
            --port 3306 \
            --cidr $IP/32