name: Deploy to AWS

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Configure kubectl (for EKS)
        run: |
          aws eks --region ${{ secrets.AWS_REGION }} update-kubeconfig --name your-eks-cluster-name

      - name: Deploy to EKS
        run: |
          # Get image tag from previous workflow (or pass manually on dispatch)
          IMAGE_TAG=${{ github.event.workflow_run.head_sha }}

          # Update K8s deployment image and rollout
          kubectl set image deployment/php-app php-container=${{ secrets.ECR_REPOSITORY }}:$IMAGE_TAG
          kubectl rollout status deployment/php-app

      # Optional: For EC2 deployment, add your deployment script here
