name: Playwright Tests

on:
  workflow_dispatch:


jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout tests
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        working-directory: ./tests
        run: |
          npm ci
          npx playwright install --with-deps

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}


      - name: Get public URL of the app
        id: get-url
        run: |
          ALB_DNS=$(aws cloudformation describe-stacks \
            --stack-name php-app-stack \
            --query "Stacks[0].Outputs[?OutputKey=='LoadBalancerDNS'].OutputValue" \
            --output text)
          echo "APP_URL=http://$ALB_DNS" >> $GITHUB_ENV

      - name: Run Playwright tests
        working-directory: ./tests
        env:
          BASE_URL: ${{ env.APP_URL }}
        run: npm run test

  stress-test:
    name: Run Stress Test
    runs-on: ubuntu-latest
    needs: e2e-tests

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Artillery
        run: npm install -g artillery

      - name: Run Stress Test with Artillery
        env:
          TARGET_URL: ${{ secrets.APP_URL }}
        run: |
          echo '
          config:
            target: "${TARGET_URL}"
            phases:
              - duration: 60
                arrivalRate: 20
          scenarios:
            - flow:
              - get:
                  url: "/"
          ' > stress-test.yml

          artillery run stress-test.yml